services:
  - type: web
    name: miss-misadame-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://miss-misadame.onrender.com 